project:
  type: website
  resources:
    - "simulazioni/"

website:
  navbar:
    left:
      - href: index.qmd
        text: Teoria
      - href: about.qmd
        text: Info

format:
  revealjs:
    theme: default
    css: stile.css
    slide-number: true